#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import vk_api
import time
import random


def main():
    # this should be user client token which can be generated by user_client_token.py script
    vk_token = ""
    # not need to add - to group id.
    group_id = ""
    argv = sys.argv[1:]

    try:
        opts, args = getopt.getopt(argv, "t:g:")
    except:
        print("Error")
    for opt, arg in opts:
        if opt in ["-t"]:
            vk_token = arg
        elif opt in ["-g"]:
            group_id = arg

    # VK API authorization
    vk_session = vk_api.VkApi(token="")
    vk = vk_session.get_api()

    # Get all albums of the group
    albums = vk.photos.getAlbums(owner_id=f"-{group_id}")["items"]

    # Get photos with less than 5 likes in all albums
    photos = []
    for album in albums:
        album_id = album["id"]
        photos_in_album = vk.photos.get(
            owner_id=f"-{group_id}", album_id=album_id, extended=1
        )["items"]
        for photo in photos_in_album:
            likes = photo.get("likes", {}).get("count", 0)
            if likes < 5:
                photos.append(photo["id"])

    # Shuffle the list of photos
    random.shuffle(photos)

    # Get the current time and tomorrow's date
    current_time = time.time()
    tomorrow = time.localtime(current_time + 86400)

    # Set the post time to 10:00 or 18:00
    post_time = time.mktime(
        (tomorrow.tm_year, tomorrow.tm_mon, tomorrow.tm_mday, 10, 0, 0, 0, 0, -1)
    )
    if post_time < current_time:
        post_time = time.mktime(
            (tomorrow.tm_year, tomorrow.tm_mon, tomorrow.tm_mday, 18, 0, 0, 0, 0, -1)
        )

    # Post photos one by one until the list is depleted
    while photos:
        photo_id = photos.pop()
        attachments = f"photo-{group_id}_{photo_id}"
        vk.wall.post(
            owner_id=-group_id, attachments=attachments, publish_date=int(post_time)
        )
        post_time += 8 * 3600  # Add 8 hours for the next post


if __name__ == "__main__":
    main()
